"""Initial Migration

Revision ID: 8401a83ff4f4
Revises: 
Create Date: 2023-04-28 10:05:58.342066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8401a83ff4f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', sa.String(length=120), nullable=True))
        batch_op.drop_index('id_UNIQUE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('id_UNIQUE', ['id'], unique=False)
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###
